// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpVfz1XDJwroGdfNQTTnz3H7OEYQZ5Scw',
    appId: '1:43673061352:web:ec5881c01ae1d4b756865d',
    messagingSenderId: '43673061352',
    projectId: 'chatapp-ff75d',
    authDomain: 'chatapp-ff75d.firebaseapp.com',
    storageBucket: 'chatapp-ff75d.appspot.com',
    measurementId: 'G-EY1X39T5VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxNFSJgzOJ1mdVrgVit1cM4iaXmp6Je-s',
    appId: '1:43673061352:android:bbad29caa9255d2656865d',
    messagingSenderId: '43673061352',
    projectId: 'chatapp-ff75d',
    storageBucket: 'chatapp-ff75d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEmCTl31JxSdlvzHsSj4tKDJwh1ef4AWY',
    appId: '1:43673061352:ios:c94249413b8df82856865d',
    messagingSenderId: '43673061352',
    projectId: 'chatapp-ff75d',
    storageBucket: 'chatapp-ff75d.appspot.com',
    iosClientId: '43673061352-adbp4ouom0h4hiut943il7pj4f5rif5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.livechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEmCTl31JxSdlvzHsSj4tKDJwh1ef4AWY',
    appId: '1:43673061352:ios:11ce63e39e945cd556865d',
    messagingSenderId: '43673061352',
    projectId: 'chatapp-ff75d',
    storageBucket: 'chatapp-ff75d.appspot.com',
    iosClientId: '43673061352-s7jlbamraj9t6vcgp0m6nm9a5usicrmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.livechat.RunnerTests',
  );
}
