// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75qcI6z_oh0UFBGrxIfEt7A-n5TL2eO8',
    appId: '1:889253187737:web:da2b31ad00eef93ff32808',
    messagingSenderId: '889253187737',
    projectId: 'mylivechat-ee30d',
    authDomain: 'mylivechat-ee30d.firebaseapp.com',
    storageBucket: 'mylivechat-ee30d.appspot.com',
    measurementId: 'G-H2X5XVF0PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXRAM21eT3pmNww4lu9_3JjcvpfWBGu4',
    appId: '1:889253187737:android:89cd4e9e71b2cb07f32808',
    messagingSenderId: '889253187737',
    projectId: 'mylivechat-ee30d',
    storageBucket: 'mylivechat-ee30d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRSAb5YDyHeOD1S5XA5t7pqZdhtxZJ4Cc',
    appId: '1:889253187737:ios:88f2b59d4938e242f32808',
    messagingSenderId: '889253187737',
    projectId: 'mylivechat-ee30d',
    storageBucket: 'mylivechat-ee30d.appspot.com',
    iosBundleId: 'com.example.livechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRSAb5YDyHeOD1S5XA5t7pqZdhtxZJ4Cc',
    appId: '1:889253187737:ios:d19effaf470ebb62f32808',
    messagingSenderId: '889253187737',
    projectId: 'mylivechat-ee30d',
    storageBucket: 'mylivechat-ee30d.appspot.com',
    iosBundleId: 'com.example.livechat.RunnerTests',
  );
}
